<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="DESKTOP-NIPPIU2" name="Default test" tests="2" failures="0" timestamp="22 Jun 2021 16:47:58 GMT" time="86.544" errors="0">
  <testcase name="a_PageLoad" time="71.33" classname="TestNGFramework.TakingScreenshot"/>
  <testcase name="b_login" time="15.104" classname="TestNGFramework.TakingScreenshot"/>
</testsuite> <!-- Default test -->
eSystemException" message="C:\Users\new\AppData\Local\Temp\screenshot5448947979148705320.png -&amp;gt; D:\Selenium Notes\screenshot\screenshot.png: The process cannot access the file because it is being used by another process.
">
      <![CDATA[java.nio.file.FileSystemException: C:\Users\new\AppData\Local\Temp\screenshot5448947979148705320.png -> D:\Selenium Notes\screenshot\screenshot.png: The process cannot access the file because it is being used by another process.

	at sun.nio.fs.WindowsException.translateToIOException(Unknown Source)
	at sun.nio.fs.WindowsException.rethrowAsIOException(Unknown Source)
	at sun.nio.fs.WindowsFileCopy.copy(Unknown Source)
	at sun.nio.fs.WindowsFileSystemProvider.copy(Unknown Source)
	at java.nio.file.Files.copy(Unknown Source)
	at org.apache.commons.io.FileUtils.copyFile(FileUtils.java:849)
	at org.apache.commons.io.FileUtils.copyFile(FileUtils.java:755)
	at TestNGFramework.TakingScreenshot.getscreenshot(TakingScreenshot.java:35)
	at TestNGFramework.TakingScreenshot.b_login(TakingScreenshot.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:100)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:646)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:811)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1129)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:746)
	at org.testng.TestRunner.run(TestRunner.java:600)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1264)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1189)
	at org.testng.TestNG.runSuites(TestNG.java:1104)
	at org.testng.TestNG.run(TestNG.java:1076)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:152)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:57)
]]>
    </failure>
  </testcase> <!-- b_login -->
</testsuite> <!-- Default test -->
